# Generated by Django 6.0.5 on 2026-05-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=100, verbose_name='Название вольера')),
                ('enclosure_type', models.CharField(choices=[('savanna', 'Саванна'), ('aquarium', 'Аквариум'), ('jungle', 'Джунгли'), ('forest', 'Лес')], default=1, max_length=10, verbose_name='Тип вольера')),
                ('capacity', models.IntegerField(default=1, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вольер',
                'verbose_name_plural': 'Вольеры',
            },
        ),
    ]
