# Generated by Django 6.0.5 on 2026-05-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
        ('enclosures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='неизвестно', max_length=100, verbose_name='Имя')),
                ('species', models.CharField(default='неизвестно', max_length=100, verbose_name='Вид')),
                ('family', models.CharField(default='неизвестно', max_length=100, verbose_name='Семейство')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('male', 'Самец'), ('female', 'Самка')], default='неизвестно', max_length=10, verbose_name='Пол')),
                ('country', models.CharField(default='неизвестно', max_length=100, verbose_name='Страна происхождения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Фото')),
                ('arrival_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='employees.employee', verbose_name='Смотритель')),
                ('enclosure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='enclosures.enclosure', verbose_name='Вольер')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'ordering': ['name'],
            },
        ),
    ]
