# Generated by Django 6.0.5 on 2026-05-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='employee',
        ),
        migrations.AddField(
            model_name='animal',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='animals', to='employees.employee', verbose_name='Смотрители'),
        ),
    ]
